### ISSUE TITLE
BUG - Large domain name break

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo#118]
#### Issue description

![image](https://github.com/ta-vivo/ta-vivo/assets/35310226/710df54e-0d00-48a6-a956-59fcc5febb0f)

#### Steps to reproduce the issue

1.  Go to the `/checks` route
2. Use the responsive mode

#### What's the expected result?

We need domain names with a long name to jump to the next line

#### What's the actual result?

One line large domain name

**Comment by robertlluberes** [comment]
The issue can be considered closed since it has been fixed by PR ##121.

**Comment by itsalb3rt** [comment]
Thanks @robertlluberes 🤝
