### ISSUE TITLE
Date delayed by a month with Telegram alert

### ISSUE THREAD

**Issue by pcabreram1234** [ta-vivo/ta-vivo#33]
#### Issue description

When one of the associated services is out, the message that is sent by telegram has the date delayed by a month.

#### What's the expected result?

-Then message sended must have de current dated.

**Comment by itsalb3rt** [comment]
Thanks @pcabreram1234 for the report, can you provide a screenshot ?

**Comment by itsalb3rt** [comment]
Thanks! The @ta-vivo/core team is now working on this.
