### ISSUE TITLE
WhatsApp integration

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo#41]
**Description**
Related with the main issue [https://github.com/ta-vivo/ta-vivo-api/issues/54](https://github.com/ta-vivo/ta-vivo-api/issues/54)

List of changes;

[x] Add the icon in integration page
[x] Created integration form
[x] Add inside the check creation
[x] Add inside the check edition

**Comment by itsalb3rt** [comment]
The `Test integration` option require an error handle when the test failed.

**Comment by Jadhielv** [comment]
@itsalb3rt Great feature. Go ahead.

**Comment by itsalb3rt** [comment]
Now the feature is completed, but require a hard test to make a sure is all the parts working.
