### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo#62]
**Is your feature request related to a problem? Please describe.**
Update dependencies to a compatible version using `yarn upgrade-interactive`

Make a sure you test before solved it.

**Comment by itsalb3rt** [comment]
@Jadhielv Avoid auto assign issue with the `hacktoberfest` label.

**Comment by Asmit2952** [comment]
Can I work on this? @itsalb3rt

**Comment by itsalb3rt** [comment]
Yes @Asmit2952 I assigned this to you 🙌

**Comment by Asmit2952** [comment]
Cool, gonna work on it now

**Comment by Asmit2952** [comment]
Hey @itsalb3rt, I installed all the dependencies and ran the app but I am getting a blank screen on localhost
