### ISSUE TITLE
UI/UX improvements in the integration section

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo#63]
**Is your feature request related to a problem? Please describe.**
Add a placeholder to the integration section when the user no have any integration. Maybe add a link to integration page.

The next image is a new check, have a blank section below the **Integrations** section;
![image](https://user-images.githubusercontent.com/35310226/192568544-31855461-ea20-4b5e-b906-74b0d76e0947.png)

**Describe the solution you'd like**
Be creative 🤠 

**Describe alternatives you've considered**
None

**Additional context**
Be free to ask to @ta-vivo/core if you have any question.

**Comment by Jadhielv** [comment]
@itsalb3rt I can take this issue.

**Comment by itsalb3rt** [comment]
Sure! @Jadhielv

**Comment by itsalb3rt** [comment]
I Take this from now
