### ISSUE TITLE
BUG Social network buttons in dark mode

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo#64]
#### Issue description
The Social media buttons have a style issue with the dark mode.

![image](https://user-images.githubusercontent.com/35310226/192571165-2eb740e4-4197-4565-88db-141d8e129b45.png)

#### Steps to reproduce the issue

1.  Enter to the APP
2. By default, the dark mode is active
3. If the dark mode no active, go to the development console in your browser, application and create a new value inside local storage `darkMode` with `true` value.

#### What's the expected result?

Like this;

![image](https://user-images.githubusercontent.com/35310226/192573236-8cf50de7-28ed-4e75-b307-24651e147820.png)

**Comment by Mustafa-Azad025** [comment]
hey @itsalb3rt ,
please Assign this task to me i will try to do it

**Comment by itsalb3rt** [comment]
Sure!

before submit your PR, make a sure you tested the UI. If you have any question, I’m here to help 🙌

**Comment by Mustafa-Azad025** [comment]
hi ,
there is an error when i start a vue server at local host and i am unable to figure out why this error is shown after installing all packages

**Comment by itsalb3rt** [comment]
According to the project documentation you need run ‘yarn’ after installing all the dependencies you need run ‘quasar dev’.

This is a Quasar Framework project. 

Ref: [https://documentation-tavivo.albert.do/front-end/](https://documentation-tavivo.albert.do/front-end/)

**Comment by Mustafa-Azad025** [comment]
Hey @itsalb3rt ,
I am unable to open the app so that i can configure please assign this to someone else , Sorry for not resolve conflict.

**Comment by itsalb3rt** [comment]
Cool, no problem. Thanks for notifying me. 🙌

**Comment by Jadhielv** [comment]
@itsalb3rt I can take this issue.

**Comment by itsalb3rt** [comment]
🙌 yes go ahead @Jadhielv

**Comment by rafieltq** [comment]
Can i take this issue?

**Comment by itsalb3rt** [comment]
Sure! @rafieltq

**Comment by rafieltq** [comment]
> #### Issue description
> The Social media buttons have a style issue with the dark mode.
> Solved! That was my results
<table>
<tr>
  <td><img src="https://i.imgur.com/337lBlD.png"/></td>
  <td><img src="https://i.imgur.com/G3avakB.png"/></td>
</tr>
</table>

**Comment by itsalb3rt** [comment]
Awesome! thanks @rafieltq

**Comment by itsalb3rt** [comment]
Ready in #69
